#!/bin/bash

set -x
set -u

cd $WORKSPACE
git clone file:///srv/packages/nova
cd nova/

# get latest version to generate the tarball
VERSION=`dpkg-parsechangelog | sed -n 's/^Version: //p'`
MAJOR_VERSION=`echo $VERSION | sed -e 's/^[\[:digit:]]*://' -e 's/[-].*//'`

cd ../source/
tar -czvf ../nova_$MAJOR_VERSION.orig.tar.gz *
cd ..

# remove original files, and copy debian files into branch
rm -rf source/*
rm source/.*
cp -R nova/debian source/

# remove patches as they won't apply to our code
rm -rf source/debian/patches
